package com.projectapp.moviesapp.my_data

import com.projectapp.moviesapp.data.model.Actor
import com.projectapp.moviesapp.data.model.Genre
import com.projectapp.moviesapp.data.model.Movie


object MovieDataSource {
    private val actorList = listOf<Actor>(
        Actor(1,"Robert Downey Jr.", "TODO: fill it"),
        Actor(2,"Chris Evans", "TODO: fill it"),
        Actor(3,"Mark Ruffalo", "TODO: fill it"),
        Actor(4,"Chris Hemsworth", "TODO: fill it"),
        Actor(5,"Robert Downey Jr.", "TODO: fill it"),
        Actor(6,"Chris Evans", "TODO: fill it"),
        Actor(7,"Mark Ruffalo", "TODO: fill it"),
        Actor(8,"Chris Hemsworth", "TODO: fill it"),
    )
    private val moviesList = listOf<Movie>(
        Movie(
            1,
            "Avengers: End Game",
            "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
            "Action, Adventure, Drama",
            "TODO fill it",
            8,
            137,
            13,
            125,
            listOf(Genre(1,"Action"),Genre(1,"Adventure"), Genre(1,"Fantasy")),
            actorList,
            false
        ),
        Movie(
            1,
            "Tenet",
            "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
            "Action, Adventure, Drama",
            "TODO fill it",
            8,
            137,
            13,
            125,
            listOf(Genre(1,"Action"),Genre(1,"Sci-Fi"), Genre(1,"Thriller")),
            actorList,
            true
        ),
        Movie(
            1,
            "Avengers: End Game",
            "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
            "Action, Adventure, Drama",
            "TODO fill it",
            8,
            137,
            13,
            125,
            listOf(Genre(1,"Action"),Genre(1,"Adventure"), Genre(1,"Fantasy")),
            actorList,
            false
        ),
        Movie(
            1,
            "Tenet",
            "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
            "Action, Adventure, Drama",
            "TODO fill it",
            8,
            137,
            13,
            125,
            listOf(Genre(1,"Action"),Genre(1,"Sci-Fi"), Genre(1,"Thriller")),
            actorList,
            true
        ),
        Movie(
            1,
            "Avengers: End Game",
            "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
            "Action, Adventure, Drama",
            "TODO fill it",
            8,
            137,
            13,
            125,
            listOf(Genre(1,"Action"),Genre(1,"Adventure"), Genre(1,"Fantasy")),
            actorList,
            false
        ),
        Movie(
            1,
            "Tenet",
            "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
            "Action, Adventure, Drama",
            "TODO fill it",
            8,
            137,
            13,
            125,
            listOf(Genre(1,"Action"),Genre(1,"Sci-Fi"), Genre(1,"Thriller")),
            actorList,
            true
        ),
        Movie(
            1,
            "Avengers: End Game",
            "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
            "Action, Adventure, Drama",
            "TODO fill it",
            8,
            137,
            13,
            125,
            listOf(Genre(1,"Action"),Genre(1,"Adventure"), Genre(1,"Fantasy")),
            actorList,
            false
        ),
        Movie(
            1,
            "Tenet",
            "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
            "Action, Adventure, Drama",
            "TODO fill it",
            8,
            137,
            13,
            125,
            listOf(Genre(1,"Action"),Genre(1,"Sci-Fi"), Genre(1,"Thriller")),
            actorList,
            true
        ),
        Movie(
            1,
            "Avengers: End Game",
            "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
            "Action, Adventure, Drama",
            "TODO fill it",
            8,
            137,
            13,
            125,
            listOf(Genre(1,"Action"),Genre(1,"Adventure"), Genre(1,"Fantasy")),
            actorList,
            false
        ),
        Movie(
            1,
            "Tenet",
            "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
            "Action, Adventure, Drama",
            "TODO fill it",
            8,
            137,
            13,
            125,
            listOf(Genre(1,"Action"),Genre(1,"Sci-Fi"), Genre(1,"Thriller")),
            actorList,
            true
        ),
        Movie(
            1,
            "Avengers: End Game",
            "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
            "Action, Adventure, Drama",
            "TODO fill it",
            8,
            137,
            13,
            125,
            listOf(Genre(1,"Action"),Genre(1,"Adventure"), Genre(1,"Fantasy")),
            actorList,
            false
        ),
        Movie(
            1,
            "Tenet",
            "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
            "Action, Adventure, Drama",
            "TODO fill it",
            8,
            137,
            13,
            125,
            listOf(Genre(1,"Action"),Genre(1,"Sci-Fi"), Genre(1,"Thriller")),
            actorList,
            true
        ),
        Movie(
            1,
            "Avengers: End Game",
            "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
            "Action, Adventure, Drama",
            "TODO fill it",
            8,
            137,
            13,
            125,
            listOf(Genre(1,"Action"),Genre(1,"Adventure"), Genre(1,"Fantasy")),
            actorList,
            false
        ),
        Movie(
            1,
            "Tenet",
            "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
            "Action, Adventure, Drama",
            "TODO fill it",
            8,
            137,
            13,
            125,
            listOf(Genre(1,"Action"),Genre(1,"Sci-Fi"), Genre(1,"Thriller")),
            actorList,
            true
        ),
        Movie(
            1,
            "Avengers: End Game",
            "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
            "Action, Adventure, Drama",
            "TODO fill it",
            8,
            137,
            13,
            125,
            listOf(Genre(1,"Action"),Genre(1,"Adventure"), Genre(1,"Fantasy")),
            actorList,
            false
        ),
        Movie(
            1,
            "Tenet",
            "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
            "Action, Adventure, Drama",
            "TODO fill it",
            8,
            137,
            13,
            125,
            listOf(Genre(1,"Action"),Genre(1,"Sci-Fi"), Genre(1,"Thriller")),
            actorList,
            true
        ),
        Movie(
            1,
            "Avengers: End Game",
            "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
            "Action, Adventure, Drama",
            "TODO fill it",
            8,
            137,
            13,
            125,
            listOf(Genre(1,"Action"),Genre(1,"Adventure"), Genre(1,"Fantasy")),
            actorList,
            false
        ),
        Movie(
            1,
            "Tenet",
            "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
            "Action, Adventure, Drama",
            "TODO fill it",
            8,
            137,
            13,
            125,
            listOf(Genre(1,"Action"),Genre(1,"Sci-Fi"), Genre(1,"Thriller")),
            actorList,
            true
        ),
        Movie(
            1,
            "Avengers: End Game",
            "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
            "Action, Adventure, Drama",
            "TODO fill it",
            8,
            137,
            13,
            125,
            listOf(Genre(1,"Action"),Genre(1,"Adventure"), Genre(1,"Fantasy")),
            actorList,
            false
        ),
        Movie(
            1,
            "Tenet",
            "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
            "Action, Adventure, Drama",
            "TODO fill it",
            8,
            137,
            13,
            125,
            listOf(Genre(1,"Action"),Genre(1,"Sci-Fi"), Genre(1,"Thriller")),
            actorList,
            true
        ),
        Movie(
            1,
            "Avengers: End Game",
            "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
            "Action, Adventure, Drama",
            "TODO fill it",
            8,
            137,
            13,
            125,
            listOf(Genre(1,"Action"),Genre(1,"Adventure"), Genre(1,"Fantasy")),
            actorList,
            false
        ),
        Movie(
            1,
            "Tenet",
            "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
            "Action, Adventure, Drama",
            "TODO fill it",
            8,
            137,
            13,
            125,
            listOf(Genre(1,"Action"),Genre(1,"Sci-Fi"), Genre(1,"Thriller")),
            actorList,
            true
        ),



    )

    fun getMovies() = moviesList
}